version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    reviewers:
      - 'MoralisWeb3/js-sdk-tean'
