import Head from 'next/head';

const Meta = () => {
  return (
    <Head>
      <title>Moralis.Auth Next.JS Demo</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Meta;
