const blockExplorers = {
  '0x1': 'https://etherscan.io/',
  '0x3': 'https://ropsten.etherscan.io/',
  '0x4': 'https://rinkeby.etherscan.io/',
  '0x2a': 'https://kovan.etherscan.io/',
  '0x5': 'https://goerli.etherscan.io/',
  '0x539': null,
  '0xa86a': 'https://cchain.explorer.avax.network/',
  '0xa869': 'https://explorer.avax-test.network/',
  '0x38': 'https://bscscan.com/',
  '0x61': 'https://testnet.bscscan.com',
  '0x89': 'https://explorer-mainnet.maticvigil.com',
  '0x13881': 'https://mumbai.polygonscan.com',
  '0xfa': 'https://ftmscan.com/',
};

export const Web3ConnectorChainConstants = {
  '0x1': {
    chainId: '0x1',
    displayName: 'Eth Mainet',
    blockExplorer: blockExplorers['0x1'],
    ticker: 'Eth',
    tickerName: 'Eth',
  },
  '0x3': {
    chainId: '0x3',
    displayName: 'Eth Ropsten',
    blockExplorer: blockExplorers['0x3'],
    ticker: 'Eth',
    tickerName: 'Eth',
  },
  '0x4': {
    chainId: '0x4',
    displayName: 'Eth Rinkeby',
    blockExplorer: blockExplorers['0x4'],
    ticker: 'Eth',
    tickerName: 'Eth',
  },
  '0x2a': {
    chainId: '0x2a',
    displayName: 'Eth Kovan',
    blockExplorer: blockExplorers['0x2a'],
    ticker: 'Eth',
    tickerName: 'Eth',
  },
  '0x5': {
    chainId: '0x5',
    displayName: 'Eth Goerli',
    blockExplorer: blockExplorers['0x5'],
    ticker: 'Eth',
    tickerName: 'Eth',
  },
  '0x89': {
    chainId: '0x89',
    displayName: 'Matic Mainet',
    blockExplorer: blockExplorers['0x89'],
    ticker: 'Matic',
    tickerName: 'Matic',
  },
};
