function createModuleItem(label, directory) {
  return {
    type: 'category',
    label,
    link: {
      type: 'doc',
      id: `api/moralisweb3/${directory}/index`,
    },
    items: [
      {
        type: 'autogenerated',
        dirName: `api/moralisweb3/${directory}`,
      },
    ],
  };
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // generate sidebar from the docs folder (or versioned_docs/<version>)
  // useful to display all docs
  sidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'Introduction',
    },
    {
      type: 'doc',
      label: 'Set Up',
      id: 'Installation',
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'api/modules',
      },
      items: [
        createModuleItem('Core', 'common-core'),
        createModuleItem('Evm Utils', 'common-evm-utils'),
        createModuleItem('Solana Utils', 'common-sol-utils'),
        createModuleItem('Aptos Utils', 'common-aptos-utils'),
        createModuleItem('Auth Utils', 'common-auth-utils'),
        createModuleItem('Streams Utils', 'common-streams-utils'),
      ],
    },
    {
      type: 'category',
      label: 'Demos',
      items: [
        {
          type: 'autogenerated',
          dirName: 'demos',
        },
      ],
    },
    {
      type: 'link',
      label: 'GitHub',
      href: 'https://github.com/MoralisWeb3/Moralis-JS-SDK',
    },
  ],
};

module.exports = sidebars;
