/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // generate sidebar from the docs folder (or versioned_docs/<version>)
  // useful to display all docs
  sidebar: [
    {
      type: 'doc',
      label: 'Introduction',
      id: 'Introduction',
    },
    {
      type: 'doc',
      label: 'Set Up',
      id: 'Installation',
    },
    {
      type: 'category',
      label: 'Modules',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'api/modules',
      },
      items: [
        {
          type: 'category',
          label: 'Core',
          link: {
            type: 'doc',
            id: 'api/moralisweb3/common-core/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/moralisweb3/common-core',
            },
          ],
        },
        {
          type: 'category',
          label: 'Evm Utils',
          link: {
            type: 'doc',
            id: 'api/moralisweb3/common-evm-utils/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/moralisweb3/common-evm-utils',
            },
          ],
        },
        {
          type: 'category',
          label: 'Solana Utils',
          link: {
            type: 'doc',
            id: 'api/moralisweb3/common-sol-utils/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/moralisweb3/common-sol-utils',
            },
          ],
        },
        {
          type: 'category',
          label: 'Auth Utils',
          link: {
            type: 'doc',
            id: 'api/moralisweb3/common-auth-utils/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/moralisweb3/common-auth-utils',
            },
          ],
        },
        {
          type: 'category',
          label: 'Streams Utils',
          link: {
            type: 'doc',
            id: 'api/moralisweb3/common-streams-utils/index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/moralisweb3/common-streams-utils',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Demos',
      items: [
        {
          type: 'autogenerated',
          dirName: 'demos',
        },
      ],
    },
    {
      type: 'link',
      label: 'GitHub',
      href: 'https://github.com/MoralisWeb3/Moralis-JS-SDK',
    },
  ],
};

module.exports = sidebars;
