name: E2E Tests

on:
  # schedule:
  # - cron: '*/60 * * * *'
  push:
    branches:
      - main
      - feat/e2e

jobs:
  e2e:
    name: Build and E2E Tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install packages
        uses: ./.github/actions/yarn-monorepo-install
      - name: Build
        run: yarn build
      - name: E2E Tests
        run: yarn test:e2e
      - name: Notify Slack If Failed
        id: slack
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_RELEASE_URL }}
